version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - backend-system
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  
  device-data-simulator:
    build: ./device-data-simulator
    image: device-data-simulator
    container_name: device-data-simulator
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      RABBITMQ_PORT: 5672
    networks:
      - backend-system
    labels:
      - "traefik.enable=false"  

  monitoring-spring:
    build: ./monitoring-microservice
    image: monitoring-microservice
    container_name: monitoring-spring
    ports:
      - "8084:8084"
    environment:
      DB_IP: monitoring-postgres-db
      DB_PORT: 5432
      DB_DBNAME: monitoring-db
      DB_USER: postgres
      DB_PASSWORD: postgres
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
      PORT: 8084
    depends_on:
      rabbitmq:
        condition: service_healthy
      monitoring-postgres-db:
        condition: service_healthy
    networks:
      - backend-system
    labels:
      - "traefik.enable=true"

  monitoring-postgres-db:
    image: postgres:16
    container_name: monitoring-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monitoring-db
    volumes:
      - monitoring-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend-system

  user-spring:
    build: ./user-management-microservice
    image: user-management-microservice
    container_name: user-spring
    ports:
      - "8081:8081"
    environment:
      DB_IP: user-postgres-db
    depends_on:
      user-postgres-db:
        condition: service_healthy
    networks:
      - backend-system
    labels:
      - "traefik.enable=true"

  user-postgres-db:
    image: postgres:16
    container_name: user-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user-db
    volumes:
      - user-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend-system

  device-spring:
    build: ./device-management-microservice
    image: device-management-microservice
    container_name: device-spring
    ports:
      - "8082:8082"
    environment:
      DB_IP: device-postgres-db
    depends_on:
      device-postgres-db:
        condition: service_healthy
    networks:
      - backend-system
    labels:
      - "traefik.enable=true"

  device-postgres-db:
    image: postgres:16
    container_name: device-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: device-db
    volumes:
      - device-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend-system

  authentication-spring:
    build: ./authentication-microservice
    image: authentication-microservice
    container_name: authentication-spring
    ports:
      - "8083:8083"
    environment:
      DB_IP: authentication-postgres-db
    depends_on:
      authentication-postgres-db:
        condition: service_healthy
    networks:
      - backend-system
    labels:
      - "traefik.enable=true"

  authentication-postgres-db:
    image: postgres:16
    container_name: authentication-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user-credentials-db
    volumes:
      - authentication-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - backend-system

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - traefik
    networks:
      - backend-system

  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    ports:
      - "80:80"      # HTTP
      - "8080:8080"  # Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./reverse-proxy/traefik.yaml:/etc/traefik/traefik.yml:ro"
      - "./reverse-proxy/dynamic:/etc/traefik/dynamic:ro"
    networks:
      - backend-system
    labels:
      - "traefik.enable=true"

volumes:
  user-pgdata:
  device-pgdata:
  authentication-pgdata:
  monitoring-pgdata:
  rabbitmq-data:

networks:
  backend-system:
    driver: bridge