entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

providers:
  docker: {}
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG
accessLog:
  filePath: "/var/log/traefik-access.log"
  bufferingSize: 0