###############################################
### LOGGING CONFIGURATIONS ###
###############################################
logging.level.root=error
logging.level.org.springframework=error
logging.level.com.example.websocketmicroservice=error


###############################################
### EMBEDDED TOMCAT CONFIGURATIONS ###
###############################################
server.port=${PORT:8085}

###############################################
### RABBITMQ CONFIG ###
###############################################
spring.rabbitmq.host=${RABBIT_HOST:rabbitmq}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.rabbitmq.password=${RABBIT_PASSWORD:guest}
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=20
spring.rabbitmq.listener.simple.concurrency=1
spring.rabbitmq.listener.simple.default-requeue-rejected=false

###############################################
### TOKEN VALIDATION ###
###############################################
jwt.secret=${JWT_SECRET:mySuperSecretKeyForJwtEncryptionMustBeAtLeast32CharsLong123!}

###############################################
### AI KEY ###
###############################################
gemini.api.key=${GEMINI_API_KEY:AIzaSyCzpbLckJYkY_anngh3T8nKKGk9JgYISoQ}